DROP TABLE IF EXISTS STATISTICS;
CREATE TABLE IF NOT EXISTS  STATISTICS
(
    ID        INTEGER           NOT NULL,
    APP       CHARACTER VARYING NOT NULL,
    URI       CHARACTER VARYING NOT NULL,
    IP        CHARACTER VARYING NOT NULL,
    TIMESTAMP TIMESTAMP         NOT NULL,
    CONSTRAINT "STATISTICS_PK"
        PRIMARY KEY (ID)
);
